# _config.yml

# Site settings
title: Your Site Title
description: Your site's description
theme: jekyll-theme-primer

# GitHub Pages settings
defaults:
  - scope:
      path: "token_pages"
    values:
      permalink: /:basename.html
