name: Log Entry

on:
  push:
    branches:
      - git-pages  # Adjust this to match your main branch name

jobs:
  log_entry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install express body-parser fs

      - name: Run server script
        run: node server/server.js
