name: Log Page Visits

on:
  push:
    branches:
      - git-pages  # Adjust this to match your git-pages branch name
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  log_visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create log file if not exists
        run: |
          touch page_visits.log || true

      - name: Log Page Visit
        run: |
          echo "$(date) - Visited URL: ${{ github.event.client_payload.page_url }}" >> page_visits.log

      - name: Commit changes
        run: |
          git config --global user.name 'selvastics'
          git config --global user.email 'cselva@uni-muenster.de'
          git add page_visits.log
          git commit -m "Log page visit"
          git push origin git-pages