name: Log Page Visits

on:
  push:
    branches:

      - git-pages  # Adjust this to match your main branch name

jobs:
  log_visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}

      - name: Create log file if not exists
        run: |
          touch page_visits.log

      - name: Log Page Visit
        run: |
          echo "${GITHUB_REPOSITORY} - $(date) - ${{ github.event_name }} - ${{ github.event.repository.html_url }} - ${{ github.event.client_payload.page_url }}" >> page_visits.log

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add page_visits.log
          git commit -m "Log page visit"
          git push origin main  # This will trigger the error

      - name: Push changes using GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token 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" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/selvastics/FRC_selva/git/commits \
          -d '{"message": "Log page visit", "content": "'$(base64 -w 0 page_visits.log)'", "branch": "main"}'
