name: Log Page Visits

on:
  push:
    branches:
      - git-pages  # Adjust this to match your git-pages branch name

jobs:
  log_visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install axios
        run: npm install axios

      - name: Log Page Visit
        run: |
          node -e "const axios = require('axios');
          const url = 'https://api.github.com/repos/selvastics/FRC_selva/contents/page_visits.log';
          const date = new Date().toISOString();
          const pageUrl = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/' + process.env.GITHUB_WORKFLOW + '/' + process.env.GITHUB_ACTION;
          const fullUrl = pageUrl + '?url=' + encodeURIComponent(process.argv[2]);
          axios.put(url, JSON.stringify({ message: 'Log page visit', content: date + ' - Visited URL: ' + fullUrl }), {
            headers: {
              'Authorization': 'token ${{ secrets.GITHUB_TOKEN }}'
            }
          })
          .then(response => console.log(response.data))
          .catch(error => console.error(error));
          " ${{ github.event.client_payload.page_url }}

      - name: Commit changes
        run: |
          git config --global user.name 'selvastics'
          git config --global user.email 'cselva@uni-muenster.de'
          git add page_visits.log
          git commit -m "Log page visit"
          git push origin git-pages
